# Generated by Django 6.0.2 on 2026-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='children_photos/', verbose_name='Фото'),
        ),
    ]
