# Generated by Django 6.0.2 on 2026-02-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0002_child_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_purchased',
            field=models.BooleanField(default=False, verbose_name='Куплено'),
        ),
    ]
